USE [master]
GO
CREATE DATABASE [SQL2016Admin]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SQL2016Admin', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\SQL2016Admin.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SQL2016Admin_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\SQL2016Admin_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SQL2016Admin] ADD FILEGROUP [InMemoryData] CONTAINS MEMORY_OPTIMIZED_DATA 
GO

ALTER DATABASE [SQL2016Admin] ADD FILEGROUP [MoreData]
GO

ALTER DATABASE [SQL2016Admin] ADD FILEGROUP [OtherData]
GO

ALTER DATABASE [SQL2016Admin] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SQL2016Admin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SQL2016Admin] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SQL2016Admin] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SQL2016Admin] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SQL2016Admin] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SQL2016Admin] SET ARITHABORT OFF 
GO

ALTER DATABASE [SQL2016Admin] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SQL2016Admin] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SQL2016Admin] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SQL2016Admin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SQL2016Admin] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SQL2016Admin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SQL2016Admin] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SQL2016Admin] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SQL2016Admin] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SQL2016Admin] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SQL2016Admin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SQL2016Admin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SQL2016Admin] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SQL2016Admin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SQL2016Admin] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SQL2016Admin] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SQL2016Admin] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SQL2016Admin] SET RECOVERY FULL 
GO

ALTER DATABASE [SQL2016Admin] SET  MULTI_USER 
GO

ALTER DATABASE [SQL2016Admin] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SQL2016Admin] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SQL2016Admin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SQL2016Admin] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SQL2016Admin] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SQL2016Admin] SET QUERY_STORE = OFF
GO

USE [SQL2016Admin]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SQL2016Admin] SET  READ_WRITE 
GO


